### PR TITLE
Add a `(Param a) => Param (In (Set a))` instance.

### PR DESCRIPTION
**Pull request by seagreen**
Also add a few simple tests.

### CODE REVIEW

**Comment by seagreen** [comment]
Definitely look this over carefully, I'm far from familiar with the codebase!

**Comment by seagreen** [comment]
Also as you can see I tried to fill out the tests some. I don't think what I added is very useful, but hopefully I can continue to improve them over time. I'll open another issue to discuss that though after we finish with this PR.

**Comment by seagreen** [comment]
Pushed up a second commit to fix compatibility issues with lts-2.

**Comment by paul-rouse** [comment]
Yes, that's looking good!  Thanks

**Pull request merged**
