### PR TITLE
Add database and table name to UnexpectedNull

### PR DESCRIPTION
**Pull request by danclien**

### CODE REVIEW

**Comment by paul-rouse** [comment]
Can you please explain why you want to do this?  Is it just for debugging, or do you want to catch the error and process the fields within your program?  The reason I ask is that I think there may be a better way of doing it.

**Comment by danclien** [comment]
We write the `UnexpectedNull` to our logs when we encounter it. This was a quick fix we did to make tracking down the issue in our database easier.

**Comment by paul-rouse** [comment]
Thanks - I wondered if it was something like that.

I think it would be much better to put this information into the `errMessage` field, which is left empty at the moment in the case of `UnexpectedNull`.  That way the `ResultError` type stays the same, so it can be done in a minor version bump, and we don't need to worry about consistency with the other constructors (which all have the same fields at present).

I'll make that change and release a new version in a few hours, and meanwhile I'll close this PR.

**Comment by paul-rouse** [comment]
Version I described released as 0.4.4 - thanks for the idea!

**Comment by danclien** [comment]
Thanks for the change. Much appreciated!

**Pull request closed without merging**
